//
// Created by Chastity Eryn on 10/14/22.
//

#ifndef MLP_S21_MULTILAYER_PERCEPTRON_SRC_MODEL_PRECEPTRON_H_
#define MLP_S21_MULTILAYER_PERCEPTRON_SRC_MODEL_PRECEPTRON_H_

class Preceptron {

};

#endif //MLP_S21_MULTILAYER_PERCEPTRON_SRC_MODEL_PRECEPTRON_H_
